### ISSUE TITLE
Can't build xui package -- ruby dependencies?

### ISSUE THREAD

**Issue by hexagon5un** [xuijs/xui#103]
So I've got Ruby installed, I run "./build" and I get:

/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- YAML (LoadError)
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
        from ./build:2:in `<main>'

Perhaps update the instructions to include loading/installing other Ruby package dependencies for the ruby-noobs?

**Comment by hexagon5un** [comment]
Seems to have been a capitalization issue?

Changing the line in ./build:

require 'YAML' 
to
require 'yaml' 
makes it build.

(PS.  I don't know shit about Ruby.  Is it case sensitive?  Why was I getting this error?)

**Comment by comparan77** [comment]
in lubuntu i had the same error but fix changing 'YAML' to 'yaml' tks hesagon5sun
