### ISSUE TITLE
q.toString() == '[object NodeList]' is inadequate

### ISSUE THREAD

**Issue by drobert** [xuijs/xui#14]
(brought over from issue 48 in the old git repo)
Code causing the problem (inside xui.fn = xui.prototype ... .find()):
    } else if (q.toString() == '[object NodeList]' { 
        ele = slice(q); 
    }

The problem here is that not every collection of DOM nodes results in [object NodeList].  Often the browser will return [object HTMLCollection], for example, via: 
    x$(document.getElementById('some_form_id').elements);

Just changing the conditional to the following solved our issues:
    } else if (q.toString() == '[object NodeList]' || q.toString() == '[object HTMLCollection]') {

**Comment by filmaj** [comment]
Thanks for bringing this up. Fixed in e0b9a267a2291ee75e2a770b50d51873f7949800 - I added the code you suggest and a test to the specs to verify issue + patch
