### ISSUE TITLE
Bug in xhr (fix included, I think)

### ISSUE THREAD

**Issue by AlexNolasco** [xuijs/xui#17]
https://github.com/xui/xui/blob/master/src/js/xhr.js line 114

```
req.handleResp = (o.callback != null) ? o.callback : function() { that.html(location, this.responseText); };   
```

Should it be this instead?

```
    req.handleResp = (o.callback != null) ? o.callback : function() { 
        that.html(location, req.responseText); // using this.responseText results in undefined (webkit)
    };
```

**Comment by filmaj** [comment]
Hmm, in Chrome 8 and Safari 5.0.3 I don't see this issue. "this" inside the makeshift callback always refers to the XHR.

Regardless I will patch it with your suggestion as a) it passes the tests and b) actually reduces the minified code by 3 bytes!

Still curious though, what browser are you seeing this in?

**Comment by filmaj** [comment]
Committed btw: 9da343a225c86595eefaaa6d25a44498ef21ab85

**Comment by AlexNolasco** [comment]
filmaj, 

I noticed this issue in  Safari 5.0.3 and iPhone 3.1.2
