### ISSUE TITLE
Negative left value breaks tween

### ISSUE THREAD

**Issue by WildFoxMedia** [xuijs/xui#20]
The following line breaks XUI

x$('#' + currentPage).tween({ left: (-(pageWidth)) + 'px' });

The error:

TypeError: Result of expression '(i+(o-i)*l).toFixed' [undefined] is not a function.

If I remove 'px' from there it doesn't throw an error, but it also doesn't do anything.

**Comment by filmaj** [comment]
Looks like this one is an issue with the underlying animation framework called [Emile](http://www.github.com/madrobby/emile). I'll pull down that code base and see if I can reproduce the error and possibly submit a patch.

**Comment by filmaj** [comment]
I added a test for this in 7efb1859e4c51bd399c6897fc02d22487e780d26

I don't see a problem in Chrome 9.0.597.102 for Mac, or Firefox 3.6.13. Where are you seeing this issue?
