### ISSUE TITLE
Blackberry 5.0 issues with HTML and before

### ISSUE THREAD

**Issue by jbuergel** [xuijs/xui#21]
Posted from the Phonegap mailing list:  the following code gives a "The page you requested could not be loaded; it is too large for the device" error when the button is clicked, both inside a Phonegap app as well as off a standard web page:

```
x$(window).load(function(e){ 
    x$('#button-add').click(function(){ 
      x$('#header').html('before','<div id="new-div">Hello!</div>'); 
    }); 
}); 


<div id="header"> 
   <h1>A header</h1> 
   <button id="button-add">Click me</button> 
</div><!-- /header --> 
```

**Comment by filmaj** [comment]
A couple of questions:
- which device OS version are you seeing this issue? i.e. 5.0.0.xxx
- which device model are you seeing this issue one? i.e. BlackBerry 8900, 9000, 9650, etc.

Let me know and I will continue looking into this one.

**Comment by filmaj** [comment]
Also, are you using [PhoneGap with WebWorks](http://www.github.com/phonegap/phonegap-blackberry-webworks) or [PhoneGap for BlackBerry 4.6](http://www.github.com/phonegap/phonegap-blackberry)?

**Comment by jbuergel** [comment]
I am using PhoneGap with Webworks, but it reproduces independently of PhoneGap - I put my page up on an external site and it had the same behavior.  I'm using the 9550 emulator, running 5.0.0.469.  As we're currently in the process of evaluating Blackberry options, I haven't tried it out on real hardware yet.  I noticed that the code above got pretty mangled, I posted it over here as well:  http://groups.google.com/group/phonegap/browse_thread/thread/99786c00cee1b760

**Comment by filmaj** [comment]
Hey,

How did you get your hands on the 9550 simulator running 5.0.0.469? If I go to the [simulator downloads](http://us.blackberry.com/developers/resources/simulators.jsp) I see a bunch of different ones but not .469.

In the mean time I will test with the 5.0.0.517 simulator and report back.

**Comment by jbuergel** [comment]
It's in the simulator pack for the Webworks install that I have, in [webworks]/simpack/5.0.0.469

**Comment by filmaj** [comment]
O sweet it is there. Thanks! I'll check with both :)

**Comment by filmaj** [comment]
Yeah the XUI test suite doesn't even finish on .469 (but does on .517). BlackBerries are so fucking bad, I don't understand how anyone uses it as a phone

**Comment by jbuergel** [comment]
Any idea if that OS is common in the wild?

**Comment by filmaj** [comment]
It's a crapshoot, no idea. RIM only provides the major revision number market shares (i.e. 4.2, 4.6, 5.0, etc.). Additionally, it is completely up to the user as to what OS revision they can run. They can easily upgrade their OS using their Desktop Manager software.

I'll take another stab at this today and see what the cause for the failing tests are, and if I can reproduce your particular error. It's funny because five or six of the xui tests fail on the revision you mention, but the test for .html('before') passes...

**Comment by filmaj** [comment]
I reworked the way .html works in b6f69beb5a1f43cf73c32c248a12a9a82acd4e53 - I'll try to rerun the tests when I get back into the office. Would be worth a shot to try again.

**Comment by jbuergel** [comment]
I'll give it a whirl, thanks.  I've largely worked around this problem
by having skeleton divs and filling them in as necessary, but it's
kind of a pain.

On Tue, May 3, 2011 at 5:39 PM, filmaj
reply@reply.github.com
wrote:

**Comment by gabrielfin** [comment]
I was having the same issue and found out that the problem were a couple of regexp in the wrap() function that the browser didn't like. To solve it, replace the following:

Line 553:

``` javascript
- attr = attrList[i].replace(/^\s*|\s*$/g, "");
+ attr = attrList[i].replace(/^\s+|\s+$/g, "");
```

Line 556:

``` javascript
- attributes[node[0]] = node[1].replace(/(["']?)/g, '');
+ attributes[node[0]] = node[1].replace(/["']/g, '');
```

**Comment by filmaj** [comment]
@gabrielfin - I have pretty much removed everything in wrap and replaced it with a simpler approach that passes all the specs. See the latest commits!

**Comment by filmaj** [comment]
With the new way xui does wrapping, I think this one's resolved. Closed!
