### ISSUE TITLE
xui not working on wp7

### ISSUE THREAD

**Issue by filmaj** [xuijs/xui#24]
apparently the IE build doesnt work on windows phone 7. run test suite on that fker!

**Comment by filmaj** [comment]
I got my hands on an HTC HD7 so I will test this out soon :)

**Comment by filmaj** [comment]
Apparently the new updates to WP7 (mango) really improved the browser. I should get on this!

**Comment by peterp** [comment]
I'll try and get hold of a device as well -

**Comment by filmaj** [comment]
The 2.3.2 tag of xui works fine with both IE mobile and WebKit builds on Windows Phone 7 Mango. Wewt!
