### ISSUE TITLE
"xui" is exactly "dick" in Russian

### ISSUE THREAD

**Issue by wargoth** [xuijs/xui#25]
Think about it ;)

**Comment by filmaj** [comment]
hmm, how about we change the name to "cock-n-balls" then ?

**Comment by wargoth** [comment]
It works :D

**Comment by wargoth** [comment]
Sorry for closing. Github should fix this too :)

**Comment by brianleroux** [comment]
This is a feature not a bug!!!

**Comment by wargoth** [comment]
I imagined how whould I explain my choice of using xui.js to my boss. Nice picture.

**Comment by sintaxi** [comment]
@brianleroux you mean enhancement ;)

**Comment by alunny** [comment]
It's intended: "jQuery" means the same in English.
