### ISSUE TITLE
XUI  ie mobile is not working on IE8 browser (desktop)

### ISSUE THREAD

**Issue by srikantkammila** [xuijs/xui#27]
I am working on a web application which should work on both mobile platform and also on desktop. For this i am using XUI js library. It is working perfectly on iphone/blackberry/android mobiles. Also working perfectly on FireFox browser. When i try using XUI ie mobile version on IE8 browser, app is broken. 

Is it possible to use XUI ie mobile version for IE browser on desktop?

**Comment by JKirchartz** [comment]
I'm having similar issues with IE7 desktop, it keeps giving me an error on x$().click saying that "Object doesn't support this property or method"... since windows phone uses IE7 I thought they'd be the same (mobile & desktop) so my site might be broken on windows phones :(

**Comment by filmaj** [comment]
Not sure, we'd have to run tests on IE8 desktop and see if it works.

Have you tried running the specs on IE desktop? Like pointing your IE8 to xuijs.com and clicking on "specs" ?

**Comment by JKirchartz** [comment]
IE 8 running on windows 7 outputs : http://jkirchartz.github.com/xuijs_tests_index-ie.pdf

**Comment by filmaj** [comment]
I will take a look at this one soon, I have IE8 on my VM.

**Comment by unjust** [comment]
I had to change the implementation of the reduce function from relying on indexOf, and also had to change using the shorthand "click" to on.("click", ...

Not sure if the two are related or if that will be the end of my problems on IE with xui.

**Comment by filmaj** [comment]
Thanks for keeping tabs on this. I'm lazy. Will get to it eventually, I _promise_ ;)

**Comment by filmaj** [comment]
DUDERS

Just tagged xui 2.3.0. This shit works on IE 6 and above.

Enjoy!

**Comment by unjust** [comment]
Thanks!

On Tue, Nov 1, 2011 at 7:43 PM, Fil Maj <
reply@reply.github.com>wrote:

> DUDERS
> 
> Just tagged xui 2.3.0. This shit works on IE 6 and above.
> 
> Enjoy!
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/xui/xui/issues/27#issuecomment-2597775

## 

sent from my iWheel
