### ISSUE TITLE
xhr doesn't work on WiMo 6.5

### ISSUE THREAD

**Issue by SamMaxwell** [xuijs/xui#3]
XMLHttpRequest doesn't exist in IE before version 7.

Instead of
   new XMLHttpRequest()
the code would need to be changed to perform
   new ActiveXObject("MSXML2.XMLHTTP")

I'm not sure if WiMo 6.5 is a target platform for XUI, but there are still some devices out there in the wild. I use IETester in IE6 mode to quickly test for WiMo 6.5.

**Comment by filmaj** [comment]
There is an IE-specific profile that you can specify during build to build a version of XUI that is aimed at IE. Try running `build --profile=ie` and using that!
