### ISSUE TITLE
iPhone innerHTML bug

### ISSUE THREAD

**Issue by jwellner** [xuijs/xui#30]
When using xuijs with PhoneGap on the iPhone the .html("string") method is failing occasionally.

I fixed this by not using html strings but creating new DOM elements instead.

Example: 

x$('#someul').html('bottom',"<li>With text</li>"); // is failing occasionally.

var li = document.createElement('li'); 
li.innerText = "With text";
x$('#someul').html('bottom',li); // is working correctly.

It looks like the innerHTML failing occurs more when using a database callback for some reason... 

I found this could be some old webkit bug?
http://comments.gmane.org/gmane.comp.handhelds.phonegap/4301
http://blog.johnmckerrell.com/2007/03/07/problems-with-safari-and-innerhtml/

**Comment by monkeeboy** [comment]
I'm experiencing something I feel may be related.

``` javascript
x$('#somediv').html('inner', '<h1>headline</h1><h2>subheadline</h2>');
```

This works exactly as expected - both the h1 and h2 are inserted.  However if I use 'bottom' to append the new html to #somediv:

``` javascript
x$('#somediv').html('bottom', '<h1>headline</h1><h2>subheadline</h2>');
```

Only the h1 is inserted... the h2 is lost.  Weird.  Curiously, it works if I wrap both in a div before passing them into the html() method:

``` javascript
x$('#somediv').html('bottom', '<div><h1>headline</h1><h2>subheadline</h2></div>');
```

Both the h1 and h2 are inserted, along with the wrapper div.  It seems like you can't pass multiple sibling elements in string form to the html() method unless you are using "inner".

This seems like a bug to me - but maybe I'm misusing the html() method somehow.  Any insight is greatly appreciated.

(This was all done in PhoneGap on iPhone iOS 4.3 Simulator).

**Comment by filmaj** [comment]
I will take a look at this early next week when I get into the office and can get someone to try this one out.

**Comment by stevengill** [comment]
Hey monkeeboy,

I tested the issue on my phone and the 4.3 simulator with the latest build of xui and it is fixed.

Here is my code: 

```
function xuiTest1(){
    x$('#test1').html('inner', '<h1>headline</h1><h2>subheadline</h2>');
}

function xuiTest2(){
    x$('#test2').html('bottom', '<h1>headline</h1><h2>subheadline</h2>');
}

function xuiTest3(){
    x$('#test3').html('bottom', '<div><h1>headline</h1><h2>subheadline</h2></div>');
}
```

And here's my markup

<pre>
    &lt;body onload="onBodyLoad()"&gt;
      &lt;h1>Hey, it's PhoneGap!&lt;/h1>
      &lt;div id='test1'>&lt;button ontouchstart="xuiTest1()">test1&lt;/button></div>
      &lt;div id='test2'>&lt;button ontouchstart="xuiTest2()">test2&lt;/button></div>
      &lt;div id='test3'>&lt;button ontouchstart="xuiTest3()">test3&lt;/button>&lt;/div>
    &lt;/body>
</pre>
