### ISSUE TITLE
window.onload? xui.ready() = DOMContentLoaded / document.readyState

### ISSUE THREAD

**Issue by i8ramin** [xuijs/xui#31]
Hi,

I noticed in some of the xui examples the following method was used to determine when the document was loaded.

``` javascript
xui(window).on('load', function() {});
```

Correct me if I am wrong, but I believe that is equivalent to doing an onLoad which waits for all resources to be loaded (images, etc.)

I haven't been able to find something similar to jQuery's $(document).ready() function and thought I'd create my own. This is what I have and it seems to work in webkit browsers:

``` javascript
xui.ready = function(fn) {
    var dr = document.readyState,
        st = setTimeout;

    if (dr) {
        st(function() {
            if (dr == 'loaded' || dr == 'complete') {
                fn()
            } else {
                st(arguments.callee, 1);
            }
        }, 1);
    } else {
        document.addEventListener('DOMContentLoaded', fn, false);
    }
};
```

This or something similar to it might be useful to include as part of xui's core.

Thank you,
Ramin

**Comment by webmat** [comment]
That code doesn't work for me. The outer setTimeout goes into an infinite loop.

But I think I'd +1 having an equivalent to jQuery's `.ready()` in xui.

It may [get complicated](https://github.com/jquery/jquery/blob/1.6.2/src/core.js#L381), though.

**Comment by webmat** [comment]
Or maybe just mix & match: there's always [domReady](https://github.com/ded/domready), found thanks to [microjs.com](http://microjs.com).

I haven't tried it yet, but it looks promising and maintained.

**Comment by filmaj** [comment]
Hmm the domReady library you linked to @webmat, although looks great, adds another 0.5 kB minified... but I also think it is worth it.

Done.
