### ISSUE TITLE
tween on value that is auto by default

### ISSUE THREAD

**Issue by rekim** [xuijs/xui#32]
I was getting the error "Object autoNaN has no method 'toFixed'" when trying to tween 'top'.

The error was avoided by adding top:'0px' to the css so it wasn't defaulting to 'auto'

**Comment by peterp** [comment]
This functionality is provided by emile: https://github.com/madrobby/emile

the documentation states the following: _for some properties you'll need to define defaults on your page's css_.

Perhaps this is a property that falls within that category?

**Comment by filmaj** [comment]
+1 on peterp's comment.

This is really an issue with emile, but am not sure whether even emile wants to deal with it... does the onus lie on the developer in this case to make sure this doesn't happen? Will close for now, if there are still issues with this one I recommend filing an issue on the emile tracker and seeing what people over there think.
