### ISSUE TITLE
css/tween inconsistencies  

### ISSUE THREAD

**Issue by rekim** [xuijs/xui#33]
marginLeft works in css, but in tween I have to use 'margin-left' or nothing happens.

**Comment by peterp** [comment]
Tween functionality is provided by a library called emile: https://github.com/madrobby/emile/blob/master/emile.js.

I've tested `marginLeft` on vanilla emile, under chrome, and it doesn't produce the desired result either. Having said that I'm sure it's a bug with emile, I'll investigate and try to provide a fix. 

Perhaps a documentation fix will suffice for XUI now.

**Comment by filmaj** [comment]
It is a bug in emile, but I've fixed it so now xui will make sure to always convert to the format emile works with. wewt
