### ISSUE TITLE
XHR failure callback

### ISSUE THREAD

**Issue by peterp** [xuijs/xui#40]
At the moment an exception is produced on failure. Is this something that XUI wants to handle as callback, I could submit a patch?

**Comment by filmaj** [comment]
Yeah it's supposed to [use the `error` property/function in the options object](https://github.com/xui/xui/blob/master/src/js/xhr.js#L122) as the error callback...

**Comment by filmaj** [comment]
Closing this, this one's cool ya?

**Comment by peterp** [comment]
Yup! I've made a pull request that updates the documentation.

**Comment by filmaj** [comment]
thanks, merged in!
