### ISSUE TITLE
Using a variable as a selector doesn't work

### ISSUE THREAD

**Issue by mazito** [xuijs/xui#55]
I don´t know if this is a bug, or if it is intended to work like this.
If I get a selector from an element attribute (the attribute contains the selector) and put it into a variable, using this variable as a selector does not work:

Example:

```
var ref= x$("#somepage").attr("href") ; // variable 'ref' contains "#idselector"
x$(ref).css("display", "block") ; // this does NOT work
```

But if I do:

```
x$(""+ref).css("display", "block") ; // enforcing a string conversion, THIS works
```

BTW: xui is awesome. I have been using jQuery for many years but it's a little heavy for mobile. 
Tested xui and its so light and compact ! Keep the good work !

**Comment by filmaj** [comment]
I think this is due to `attr` returning an array (since xui can potentially match multiple objects).

If you change your second xui call to:

`x$(ref[0]).css("display","block);`

That should work.

I'm open to discussion on this one but for now I will close the issue.
