### ISSUE TITLE
Consider adding content-type:  'application/x-www-form-urlencoded' for every XHR POST request

### ISSUE THREAD

**Issue by Reinmar** [xuijs/xui#57]
Hi,
Now I have to set this header every time I'm doing post request. Prototype for example always (even for get requests) add this header. Thanks to this it works with e.g. PHP's $_POST variable.

**Comment by filmaj** [comment]
Fixed in 454bd6d. Didn't tag it as I didn't think it was necessary, but yeah, it's there anyways
