### ISSUE TITLE
Cannot customize Content-Type header on xhr() POST

### ISSUE THREAD

**Issue by arkusuma** [xuijs/xui#66]
My web service was strictly accepting request with Content-Type: application/json
I cannot get that kind of header in XUI.  The code below always produce
Content-Type: application/x-www-form-urlencoded, application/json

Code:

```
x$("#result").xhr("/mobile.asmx/arsip", {
    method: "post",
    async: true,
    data: '{"hal": 1}',
    headers: { "Content-Type": "application/json" },
});
```

**Comment by jerose** [comment]
This means it wont work with Yahoo API's using direct OAuth since it requires a Content-Type of "application/json" on POST also. Would seem better to have "application/x-www-form-urlencoded" there only as a default content type on POST, but allow it to be overwritten.
