### ISSUE TITLE
.html() doesn't work on winmobile 6.5

### ISSUE THREAD

**Issue by teson2000** [xuijs/xui#67]
x$('h2').html('set this..');

seem to have no effect on pda device running winmo6.5pro, ce os 5.2

**Comment by filmaj** [comment]
What build profile did you use? The stock one or the IE-specific one?

**Comment by teson2000** [comment]
Thanks for your feed back. xui-ie-2.3.2.min.js used.

<p id="comment">_init_</p>

<script type="text/javascript">
x$('#comment').html('wont work');
var works = document.getElementById('comment');
works.innerHTML('good');
...

**Comment by teson2000** [comment]
(works in PC IE, not PDA running winmo 6.5)
