### ISSUE TITLE
anyone still working on xui? 

### ISSUE THREAD

**Issue by acturbo** [xuijs/xui#88]
i'm trying to decide which mobile js framework to commit to, xui seems like an excellent option (JoApp is my alternative) but i see very little activity lately. Is this project still active? thanks.

**Comment by andCulture** [comment]
+1

**Comment by afryer** [comment]
+2

**Comment by sebo** [comment]
+3 :)

**Comment by brianleroux** [comment]
we're back

**Comment by afryer** [comment]
should we re-open this?
