### ISSUE TITLE
Can't dynamically create <td> elements

### ISSUE THREAD

**Issue by quaelin** [xuijs/xui#91]
``` js
   var
      table = xui('<table><tr></tr></table>'),
      tr = table.find('tr')
  ;
  tr.bottom('<td></td>');  // does not work
```

XUI seems to have issues with dynamically creating `<tr>` or `<td>` elements.  Am I missing something, or is this a bug?

**Comment by afryer** [comment]
``` javascript
var
      table = xui('<table><tr></tr><tr></tr><tr></tr><tr></tr></table>'),
      tr = table.find('tr');

    tr.inner('<td>');

console.log(table.html())
```

Example given is malformed html as the td needs to go into the tr.

**Comment by quaelin** [comment]
I don't understand how my example is malformed.  My understanding of `tr.bottom()` is exactly that it should place content inside the `<tr>` (specifically at the bottom), similar to how jQuery's `.append()` works.  Is this wrong?

**Comment by afryer** [comment]
My understanding is that `.html()` and `.inner()` are like jQuery's `.append()`  and `.bottom()` would place the element at the bottom of the element, underneath it e.g.

```
<tr></tr>
<td></td>

```

I could quite easily be wrong though

**Comment by afryer** [comment]
In fact I think I am with `.bottom()` behaviour.
